- name: install apache2
  yum:
    name: httpd
    state: present
    update_cache: yes
- name: service apache2
  service:
    name: httpd
    enabled: yes
    state: started
- name: httpd.conf setting
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    notify:
      - Restart httpd
- name: firewalld http open
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
- name: selinux permissive
  selinux:
    policy: targeted
    state: permissive
- name: update epel-release
  yum:
    name: epel-release
    state: present
- name: remi-release 7 download
  yum:
    name: http://ftp.riken.jp/Linux/remi/enterprise/remi-release-7.rpm
    state: present
- name: install php
  yum:
    name: php,php-mysqlnd
    enablerepo: remi-php74
    state: present
- name: restart httpd
  service:
    name: httpd
    state: restarted
  

