---
# handlers file for wordpress

- name: Restart apache2
  service:
    name: apache2
    state: restarted
- name: Restart httpd
  service:
    name: httpd
    state: restarted
 


       
       
      

      

